//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZProject.TZService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TZService.ITZService")]
    public interface ITZService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITZService/GetLockerBankXML", ReplyAction="http://tempuri.org/ITZService/GetLockerBankXMLResponse")]
        string GetLockerBankXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITZService/GetLockerBankXML", ReplyAction="http://tempuri.org/ITZService/GetLockerBankXMLResponse")]
        System.Threading.Tasks.Task<string> GetLockerBankXMLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITZServiceChannel : TZProject.TZService.ITZService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TZServiceClient : System.ServiceModel.ClientBase<TZProject.TZService.ITZService>, TZProject.TZService.ITZService {
        
        public TZServiceClient() {
        }
        
        public TZServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TZServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TZServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TZServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLockerBankXML() {
            return base.Channel.GetLockerBankXML();
        }
        
        public System.Threading.Tasks.Task<string> GetLockerBankXMLAsync() {
            return base.Channel.GetLockerBankXMLAsync();
        }
    }
}
